{{- $values := $.Values.rpcDaemons }}
{{- $componentName := "rpcdaemons" }}
{{- $componentLabel := include "erigon.componentLabelFor" $componentName }}
{{- if $values.enabled }}
{{- if $.Values.prometheus.podMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "erigon.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "erigon.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "erigon.selectorLabels" . | nindent 6 }}
      {{- $componentLabel | nindent 6 }}
  podMetricsEndpoints:
  - port: http-rpcmetrics
{{- end }}
{{- end }}